// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYxZVsoi7l6iflPoqO3wdBnGGNHA18i7Q',
    appId: '1:1065061223974:web:0e70d7cd67cd6fc69d20e7',
    messagingSenderId: '1065061223974',
    projectId: 'quick-mart-3d6b5',
    authDomain: 'quick-mart-3d6b5.firebaseapp.com',
    storageBucket: 'quick-mart-3d6b5.firebasestorage.app',
    measurementId: 'G-69J66WF6XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRL7tnx9TZRHX8kRbC6UgRrNujLZCm6B4',
    appId: '1:1065061223974:android:c332ca3a7738a96b9d20e7',
    messagingSenderId: '1065061223974',
    projectId: 'quick-mart-3d6b5',
    storageBucket: 'quick-mart-3d6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3YhbDq7VMAVYXwteKhJIlLi1LMdOJDM',
    appId: '1:1065061223974:ios:05f9c0cb8e6967e29d20e7',
    messagingSenderId: '1065061223974',
    projectId: 'quick-mart-3d6b5',
    storageBucket: 'quick-mart-3d6b5.firebasestorage.app',
    iosBundleId: 'com.example.quickMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3YhbDq7VMAVYXwteKhJIlLi1LMdOJDM',
    appId: '1:1065061223974:ios:05f9c0cb8e6967e29d20e7',
    messagingSenderId: '1065061223974',
    projectId: 'quick-mart-3d6b5',
    storageBucket: 'quick-mart-3d6b5.firebasestorage.app',
    iosBundleId: 'com.example.quickMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYxZVsoi7l6iflPoqO3wdBnGGNHA18i7Q',
    appId: '1:1065061223974:web:793303a359b18a739d20e7',
    messagingSenderId: '1065061223974',
    projectId: 'quick-mart-3d6b5',
    authDomain: 'quick-mart-3d6b5.firebaseapp.com',
    storageBucket: 'quick-mart-3d6b5.firebasestorage.app',
    measurementId: 'G-5TZQBNYL66',
  );
}
